### ISSUE TITLE
Setting up vault failed

### ISSUE THREAD

**Issue by karesztrk** [mylofi/local-vault#4]
Hey, 

I have just tried your test page @ https://mylofi.github.io/local-vault/, but I always receive an error. Regardless of the browser. 

![image](https://github.com/user-attachments/assets/99bfd802-975d-4e70-a84a-4c49350e8984)

Let me know if I can help further with the investigation.

  Hardware:
     Dell Latitude 5411
  OS: Linux 6.10 Garuda Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 16.71 GB / 30.96 GB

**Comment by getify** [comment]
I think linux doesn't support WebAuthn.

**Comment by getify** [comment]
What browser are you using on linux? Also, could you try running this in your browser's dev console?

```js
await PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable();
```

Does it report `true` or `false`?

**Comment by karesztrk** [comment]
> What browser are you using on linux? Also, could you try running this in your browser's dev console?
> 
> ```js
> await PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable();
> ```
> 
> Does it report `true` or `false`?

Yes, it's returning `false`. I'm using Firefox. I did not know that this API is OS-specific.  
Could you add an appropriate error message?

**Comment by getify** [comment]
Have you been able to use passkeys in any other apps or sites on that device?

For example: https://www.passkeys.io/

**Comment by getify** [comment]
BTW the "user verifying" part of that API name, means an authenticator that can require the user affirmatively interact with the device to prove they're there, instead of some authenticators (like external usb yubikeys or whatever), which allow silent verification with no interaction.

The way we're using passkeys, we require user verification, so it narrows the types of biometric devices that are compatible.

**Comment by karesztrk** [comment]
> Have you been able to use passkeys in any other apps or sites on that device?
> 
> For example: https://www.passkeys.io/

I have just realized that the built-in fingerprint reader driver was missing. So I installed it from AUR (https://aur.archlinux.org/packages/libfprint-2-tod1-broadcom).
I could enroll a fingerprint but Firefox is not reading it. I need further investigation.

Ref:

- https://aur.archlinux.org/packages/libfprint-2-tod1-broadcom (build was unsuccessful without installing glib2)
- https://wiki.archlinux.org/title/Fprint

**Comment by getify** [comment]
It might be this: https://github.com/mylofi/webauthn-local-client/issues/11

**Comment by getify** [comment]
@karesztrk 

Can you please [try the steps indicated in this FF bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1915919) and see if that also fails for you on FF linux?

**Comment by getify** [comment]
Update: looks like the FF folks verified that they do in fact have a bug, and they're fixing it.

**Comment by karesztrk** [comment]
> Update: looks like the FF folks verified that they do in fact have a bug, and they're fixing it.

In fact, I receive the following error:

`DOMException: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.`

**Comment by getify** [comment]
Hmmm... that's weird and doesn't match the other bug I filed with them.

Did you try that other passkey demo URL?

**Comment by karesztrk** [comment]
I tried https://www.passkeys.io/. And its correctly poping up the fingerprint prompt next to the address bar. But nothing happens after that.
Your app tests behave the same.

**Comment by getify** [comment]
When you click the "Sign in with passkey" button on that demo?

**Comment by karesztrk** [comment]
passkey.io:
![image](https://github.com/user-attachments/assets/858826e2-ce0c-4869-b8e7-53f331e400b2)

your tests, after the wizard steps:
![image](https://github.com/user-attachments/assets/858826e2-ce0c-4869-b8e7-53f331e400b2)
![image](https://github.com/user-attachments/assets/6e8b4c63-c009-4263-988f-ea21d9e8a099)

**Comment by getify** [comment]
Clearly there's a settings difference between the way I'm using WebAuthn and the way that passkeys.io site is using it. The problem is, I don't know what the settings difference is, and it's very hard for me to debug that remotely and asynchronously through messages here.

I had thought maybe I could set up a special site just for you to go step-by-step through, to see which part specifically is failing. But that's a bit more work than I've had time to get involved in yet.

----

In the interim, if you're able to do any diagnosing of the differences, that'd be helpful. I'd suggest switching away from using the vault test-bed, to using this: https://mylofi.github.io/webauthn-local-client/ That's *just* the webauthn stuff, without any of the vault/encryption stuff on top. I think the problem is right at that core, so hopefully this makes it easier to diagnose.

You could also run that WALC test-bed locally (instructions in its repo), which tests against the unminified source files, thus giving better error stack traces with correct line numbers, etc.

**Comment by karesztrk** [comment]
Okay, lets close this until i find something

**Comment by getify** [comment]
NOTE: the FF bug mentioned in this thread has been verified as fixed as of FF 132 (current stable).

**Comment by getify** [comment]
Well, I had originally hoped that maybe the error you were having was related to FF's bug. It seemed like that was a long-shot, though. And if you're still having the issue, then it clearly wasn't the FF issue.

As I said earlier in the thread, I can't replicate your issue. So without further info, there's not much I can do.

**Comment by karesztrk** [comment]
@getify I have just listened you in the localfirst.fm. What you said resonates with me so much. I would like to join to you on your mission. Is there a way to join you or a community around it?
Thanks
